name: validate

on:
  push:
  pull_request:

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v6
      - name: Run tests with coverage
        run: |
          uv run --with-requirements requirements-dev.txt coverage run -m pytest
          uv run --with-requirements requirements-dev.txt coverage report --fail-under=85
